### ISSUE TITLE
retrieve.py  

### ISSUE THREAD

**Issue by ShayDuane** [zjunlp/RAP#3]
D:\Users\ShuaiqiDuan\Desktop\Research\DL\NLP_Pytorch\RAP\RAP\retrieval\retrieve.py:14: DeprecationWarning: Using positional arguments for APIs is deprecated and will be disabled in 8.0.0. Instead use only keyword arguments for all APIs. See https://github.com/elastic/elasticsearch-py/issues/1698 for more information
  if es.indices.exists(index_name):
E:\anaconda\envs\PyTorch\lib\site-packages\elasticsearch\connection\base.py:200: ElasticsearchWarning: Elasticsearch built-in security features are not enabled. Without authentication, your cluster could be accessible to anyone. See https://www.elastic.co/guide/en/elasticsearch/reference/7.17/security-minimal-setup.html to enable security.
  warnings.warn(message, category=ElasticsearchWarning)
Traceback (most recent call last):
  File "D:\Users\ShuaiqiDuan\Desktop\Research\DL\NLP_Pytorch\RAP\RAP\retrieval\retrieve.py", line 180, in <module>
    construct_store(es, data_name)
  File "D:\Users\ShuaiqiDuan\Desktop\Research\DL\NLP_Pytorch\RAP\RAP\retrieval\retrieve.py", line 17, in construct_store
    data = read_data_from_file(file_name=file_name)
  File "D:\Users\ShuaiqiDuan\Desktop\Research\DL\NLP_Pytorch\RAP\RAP\retrieval\retrieve_utils.py", line 59, in read_data_from_file
    inputs = open('store/' + file_name, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'store/nyt_store.json'
how can i solve it ?

**Comment by littlefive5** [comment]
We update the store in readme,  you can download it from the link.

**Comment by ShayDuane** [comment]
Thank you very much!
